CREATE DATABASE IF NOT EXISTs `travel-attraction` CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTs `travel-auth` CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTs `travel-country` CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTs `travel-favorite` CHARACTER SET utf8mb4;